language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
script: bundle exec rspec
before_install:
  # fixes Travis CI error: NoMethodError: undefined method `spec' for nil:NilClass
  - gem install bundler
